### ISSUE TITLE
Reorganize the comments placement 

### ISSUE THREAD

**Issue by jbourcie** [correctexam/corrigeExamFront#236]
It will be nice to find a way to have all the possible comments directly accessible without scrolling

**Comment by barais** [comment]
First idea is to remove layout option (realign image, page shifting, no alignement) in a specific side bar https://primeng.org/sidebar

Next could be to transform comments as a simple button/div with title and mark in one line and description in tooltip. It could allow to keep probably ten to twelve comments on the same screen. Next grading must be a floating div to be sure we could grade the sheet without scrolling

**Comment by barais** [comment]
@jbourcie 

I am curious to see if it is better ?

**Comment by nthiery** [comment]
I just discovered the compact view for comments. That helps a lot and was something I wanted to suggest when I last used correctExam. Thanks!

Potential further suggestions:
- arrange the comments in a grid rather than a vertical list?
- let the user scroll through the comments without scrolling the copy view itself

**Comment by barais** [comment]
> let the user scroll through the comments without scrolling the copy view itself
done https://github.com/correctexam/corrigeExamFront/pull/405

I also decrease the size of comment in minimized view to show a maximum number of comments without scrolling
