### ISSUE TITLE
Issue with the handsontable license

### ISSUE THREAD

**Issue by arnobl** [correctexam/corrigeExamFront#259]
handsontable does not have a open-source license.
https://github.com/handsontable/handsontable/blob/develop/LICENSE.txt
Our usage does not match their terms: 
'If your use is strictly personal or solely for evaluation purposes, meaning for the purposes of testing the suitability, performance, and usefulness of this software outside the production environment, you agree to be bound by the terms included in the "handsontable-non-commercial-license.pdf" file'

However our usage matches the terms and conditions of the official pdf of the license (but redistribution we must fix):
https://github.com/handsontable/handsontable/blob/develop/handsontable-non-commercial-license.pdf

Do not know if our MIT license is compatible with this license.

**Comment by barais** [comment]
I will investigate,

it also means that it could be great to generate the SBOM for the back, the front, ...
And do a global licence check

**Comment by barais** [comment]
@arnobl I confirm the issue. 

Please below the email of Tom from Handsontable. Hi Olivier,
 
Thanks for taking the time to write us. Handsontable in the version you are using is not an MIT license. The highest version of the MIT license is 6.2.2. Your project is fine and is considered for using the non-commercial license, but since it is an MIT project, it can then be used by a third party to use for commercial usage, which we don't agree to. Handsontable in any version above 6.2.2 cannot be used in an MIT license unless you make sure that any project using your app on the MIT license will reach out to us to talk about their usage. The second option is for the app with the Handsontable component to be a separate instance not on the MIT license but still be free to any teacher that needs it. 
 
If you have any questions about the above, please let me know. 
Kind regards,

—

**Comment by barais** [comment]
I think, I will try to move to https://github.com/revolist/revogrid
