### ISSUE TITLE
Investigate the possibility to correct questions and students randomly

### ISSUE THREAD

**Issue by arnobl** [correctexam/corrigeExamFront#389]
Currently, the marking order is the scanning order. This may introduce a marking bias.
Some folks talked me about a feature to randomly mark either or both questions and students.

This rises different questions:
- when the order is defined? 
   - Once, when starting the marking? 
   - Performed on each 'next' command while marking a question? So the original order is kept but the random marking is done 'live'. This possibility would make the readability of the marking status page less efficient IMO. But it does not require any backend change and really follows a random process by shuffling the marking during the whole marking session.

**Comment by barais** [comment]
I think for the first part randomly mark either students for each question. It could be done easily.

For the second part, we need to decide how the professor could tell us that this question is part of a group of questions (so the order is important). For me it is linked to the requirement of @nthiery. #333

**Comment by arnobl** [comment]
Indeed, the notion of 'exercise' (composed of questions) should be added.
This is quite easy to add it in the latex template.
More challenging to change the DB and the front without breaking the app.

**Comment by nthiery** [comment]
Hi!

Randomizing the student order would indeed be a nice feature to avoid systematic bias.
On the other hand, in our use cases so far, I don't see a need for randomizing the question
order; on the contrary, instructors choose in which order they treat question based on
the coordination with others, potential dependencies between questions, granularity, etc.

That being said, grading strategies vary a lot; so if it's opt-in and useful for others, sure :-)

**Comment by arnobl** [comment]
I agree. randomizing the questions is far to be a nominal case. Should focus on students. This makes the feature more simple since it does not require 'exercises'.

**Comment by nthiery** [comment]
Thinking twice about it: it might well be (mostly) a frontend feature rather than backend: while grading, the order you have in your head is about the (last few) copies you have seen; with scenarii like "oh, a couple copies ago, I saw a similar mistake, let's create a new comment and come back to apply it". So the user interface while grading a given question could have the following actions:
- New: Pick a random copy that was assigned to no-one, and assign it to me
- Previous: Move back one copy, in the order they were assigned to me
- Next: Move forward one copy, in the order they were assigned to me
- Unassign the current copy.

Implementation:
- For each question, the front end maintains a sorted list of copies that were assigned to me
- For each question, the back end maintains a set of unassigned copy

Simpler variant that requires no backend change:
- New: Pick a random copy that is not yet graded; add it to the list L of copies I have seen
- Previous: Move back one copy, in the order of L.
- Next: Move forward one copy, in the order of L.

Pros: no risk of a copy not being graded because it got assigned to someone that stopped grading
Cons: the same copy may be seen by several people


In either cases, this makes it easy for several graders to grade the same question without stepping on each other: you don't have to develop strategies such as "I start from the beginning; you start from the end".

**Comment by barais** [comment]
@arnobl @nthiery . I just did a first implementation. I will do some test tomorrow and if it works smoothly. I will deploy this feature and write some doc to show how it works.

**Comment by nthiery** [comment]
Nice! Just in time for @hivert's exam :-)
