### ISSUE TITLE
Suggestion - Reduce the time between keyboard shortcuts

### ISSUE THREAD

**Issue by o-laurent** [correctexam/corrigeExamFront#439]
Hello, 

Thanks for your awesome work. Would it be possible to decrease the minimum time between consecutive keyboard shortcuts? 

This could be helpful for questions with multiple comments yet very easy to correct.

Thanks again!

**Comment by barais** [comment]
Yeah, I will try to manage that, 
the delay is mainly due to the fact that we create a request to the server to update the correction and we wait for the server's response before allowing the next interaction. It is necessary to set up a pipe of requests to be executed by sequencing them. It will then be necessary to block if more than X requests are to be executed.

**Comment by barais** [comment]
I will try something like that for adding or removing comment

https://stackoverflow.com/questions/56126246/process-request-sequentially
